### PR TITLE
Consistent naming when deserializing yaml

### PR DESCRIPTION
**Pull request by johanlindfors**
Some of the properties in the model have inconsistent naming schemes, this PR fixes those.

Question: answerset -> answerSet
PracticeLevel: maturitylevel -> maturityLevel

Please note that this change might break applications that have implemented an explicit naming of these properties while deserializing the provided yaml.

### CODE REVIEW

**Comment by dkefer** [comment]
We should include this change in version 2.1.

**Comment by johanlindfors** [comment]
How can I help?

**Comment by dkefer** [comment]
@johanlindfors with testing, if you like. As the next version will be 2.1, merging into the develop branche now

**Comment by johanlindfors-ts** [comment]
My tests works fine with the latest changes in develop.

**Pull request merged**
